# I/O
input_directory: /capstor/scratch/cscs/sriva/model128/
# input_file: AR_385_Cut_64x64x128_mirrorxy-CRD_I_V0-B0_fix_conv_KQ_MC.pmd
# input_file:      cai_0Bx_0By_0Bz_0Vx_0Vy_0Vz_GT4_5x5x133_it100.pmd
input_file:      small_ssd_from3D_8x8x143.h5
### input_file:     FALC93_70_v0_B20
# frequency_file:  frequency/fal-c_299/frequency.dat
frequency_file: frequency/96F/frequency.dat

output: true
output_overwrite_prevention: true

## Lustre filesystem at CSCS:
## Before running solar_3d, prepere the output directory with:

## > mkdir -p $SCARTCH/output/
## > lfs setstripe -c -1 -S 4M $SCARTCH/output/ 

## This will ensure that the output files are distributed across all the OSTs, 
## and not just one, which would cause a bottleneck.
write_whole_3D_field_hdf5: true
write_text_output: false

output_directory: /capstor/scratch/cscs/sriva/model128_OUT/new_h5_test/v2

use_B: true
use_Vb: true

pc_use_J_KQ: true

use_continuum: false
formal_solver: DELO_linear

set_uniform_B: false
B_field: [5.0, 1.0, 1.0]

use_D2_from_input: true

emissivity_model: PRD  
# emissivity_model: CRD_limit 

# used only for FAL-C input
N_theta: 8
N_chi:   16
input_cul_string:  ""

use_prec: true


solver:
  ksp_solver_type: KSPFGMRES
  ksp_rtol: 1e-7
  ksp_max_it: 15

prec:
  pc_solver_type: KSPFGMRES
  pc_rtol: 5e-4
  pc_max_it: 17

default_chi: &default_chi 0.0

arbitrary_beams: 
 - mu: 0.1
   chi: *default_chi

 - mu: 0.3
   chi: *default_chi
    
 - mu: 0.7
   chi: *default_chi

 - mu: 1.0
   chi: *default_chi

 - mu:  3.30009478207572e-01
   chi: 1.96349540849362e-01
